version: "3.6"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db

  redis:
    image: "redis"

  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - db
      - redis
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  proxy:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3080:80"
    depends_on:
      - api
      - client

volumes:
  db:
    driver: local
# networks:
#   complex:
#     driver: bridge
# version: "3"
# services:
#   db:
#     image: "postgres:10"
#     restart: always
#     volumes:
#       - postgresdata:/data/postgres
#       - postgreslogs:/logs:z
#     # Make Postgres log to a file.
#     # More on logging with Postgres: https://www.postgresql.org/docs/current/static/runtime-config-logging.html
#     command: /bin/bash -c "mkdir -p /logs && chmod -R 777 /logs && postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=postgres
#     networks:
#       - complex
# redis:
#   image: "redis:latest"
#   networks:
#     - complex
# server:
#   build:
#     dockerfile: Dockerfile.dev
#     context: ./server
#   volumes:
#     - /app/node_modules
#     - ./server:/app
#   environment:
#     - REDIS_HOST=redis
#     - REDIS_PORT=6379
#     - PGUSER=user
#     - PGHOST=postgres
#     - PGDATABASE=postgres
#     - PGPASSWORD=password
#     - PGPORT=5432
#   networks:
#     - complex
#   depends_on:
#     - postgres
#     - redis

# volumes:
#   postgresdata:
#     driver: local
#   postgreslogs:
#     driver: local
